name: jdk-maven-node Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NODE_VERSION: [18, 20]
        JAVA_VERSION: [17, 21]
    steps:
      - uses: actions/checkout@v2
      - name: Docker build and publish
        env:
          MVN_VERSION: ${{ matrix.MVN_VERSION }}
          JAVA_VERSION: ${{ matrix.JAVA_VERSION }}
          NODE_VERSION: ${{ matrix.NODE_VERSION }}
          DOCKER_IMAGE_TAG: atools/jdk-maven-node:jdk${{ matrix.JAVA_VERSION }}-node${{ matrix.NODE_VERSION }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u atools -p $DOCKER_PASSWORD
          docker build --build-arg NODE_VERSION=$NODE_VERSION --build-arg MAVEN_JDK_VERSION=3-eclipse-temurin-$JAVA_VERSION -t ${DOCKER_IMAGE_TAG} .
          docker push ${DOCKER_IMAGE_TAG}
